// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  defaultLanguage: 'en-US',
  supportedLanguages: [
    { code: 'en-US', flag: 'flag_uk.png' },
    { code: 'fr-FR', flag: 'flag_france.png' },
    { code: 'nl-NL', flag: 'flag_netherlands.png' },
    { code: 'es-ES', flag: 'flag_spain.png' }
  ],
  api_url: '/rest-z4d/1',
  keysBoundActive: 'alt+z+i+g',
  keysBoundInactive: 'alt+s+t+o+p',
  refresh: 7000,
  linkToConsent: 'https://github.com/zigbeefordomoticz/wiki',
  trackerUrl: 'https://z4d.pipiche.net/',
  siteId: '3'
};
